;; -*- mode: Emacs-Lisp -*-
;; This is bindings loaded by user.el
(setq ns-function-modifier 'hyper)  ; make Fn key do Hyper
;; (setq ns-function-modifier 'hyper)  ; make Fn key do Hyper
(define-key input-decode-map [?\C-m] [C-m])
(global-set-key (kbd "<f8>") 'menu-bar-open)
(global-set-key (kbd "<f10>") 'toggle-frame-maximized)
(global-set-key (kbd "M-e") 'sentence-nav-forward)
(global-set-key (kbd "<escape> M-e") 'forward-sentence)
(global-set-key (kbd "<escape> M-a") 'backward-sentence)
(global-set-key (kbd "<escape> C-e") 'end-of-line)
(global-set-key (kbd "<escape> C-a") 'beginning-of-line)
(global-set-key (kbd "M-=") 'count-words)
(global-set-key (kbd "M-E") 'sentence-nav-forward-end)
(global-set-key (kbd "M-a") 'sentence-nav-backward)
(global-set-key (kbd "M-A") 'sentence-nav-backward-end)
(global-set-key (kbd "<C-m>") 'exchange-point-and-mark)
(global-set-key (kbd "s-h") 'help-command)
(global-set-key (kbd "s-h s-h") 'ns-do-hide-emacs)
(global-set-key (kbd "s-H") 'ns-do-hide-others)
(global-set-key (kbd "H-h") 'ns-do-hide-others)
(global-set-key (kbd "s-l") 'async-shell-command)
(global-set-key (kbd "C-M-{")	'previous-buffer)
(global-set-key (kbd "C-M-}")	'next-buffer)
(global-set-key (kbd "C-s-{")	'jj/previous-user-buffer)
(global-set-key (kbd "C-s-}")	'jj/next-user-buffer)
(global-set-key (kbd "C-M-f") 'sp-forward-sexp)
(global-set-key (kbd "C-M-b") 'sp-backward-sexp)
(global-set-key (kbd "C-M-d") 'sp-down-sexp)
(global-set-key (kbd "C-M-u") 'sp-backward-up-sexp)
(global-set-key (kbd "C-x C") 'jj/save-buffers-kill-terminal)
(global-set-key [(super ?h)] 'help-command)
(global-set-key [(control ?h)] 'delete-backward-char)
(global-set-key (kbd "M-h") 'jj/delete-backward-word)
(global-set-key (kbd "M-s p") 'mark-paragraph)
(global-set-key (kbd "M-s [") 'mark-paragraph)
(global-set-key (kbd "M-s {") 'mark-paragraph)
(global-set-key (kbd "M-s M-p") 'mark-paragraph)
(define-key org-mode-map (kbd "M-s M-p") 'org-mark-element)
(define-key org-mode-map (kbd "M-s p") 'org-mark-element)
(define-key org-mode-map (kbd "M-h") 'jj/delete-backward-word)
(global-set-key (kbd "C-x 2") 'split-window-vertically)
(global-set-key (kbd "C-x 3") 'split-window-horizontally)
(global-set-key (kbd "<C-s-left>") 'shrink-window-horizontally)
(global-set-key (kbd "<C-s-right>") 'enlarge-window-horizontally)
(global-set-key (kbd "<C-s-up>") 'shrink-window)
(global-set-key (kbd "<C-s-down>") 'enlarge-window)
(global-set-key (kbd "<escape> 9") 'insert-parentheses)
(global-set-key (kbd "<escape> SPC") 'jj/insert-space-in-front)
(global-set-key (kbd "M-S-SPC") 'jj/insert-space-in-front)
(global-set-key (kbd "<escape> 4") 'jj/insert-dollar-sign)
(global-set-key (kbd "<escape> d") 'jj/insert-dollar-sign)
(global-set-key (kbd "<escape> $") 'jj/insert-double-dollar-dollar-sign)
(global-set-key (kbd "<escape> [") 'jj/insert-brackets)
(global-set-key (kbd "<escape> =") 'org-strikethrough-region-or-point)
(global-set-key (kbd "<escape> +") 'org-strikethrough-region-or-point)
(global-set-key (kbd "<escape> {") 'jj/insert-brackets-alt)
(global-set-key (kbd "<escape> ]") 'jj/insert-brackets-alt)
(global-set-key (kbd "<escape> b") 'sp-splice-sexp)
(global-set-key (kbd "<escape> 0") 'sp-splice-sexp)
(global-set-key (kbd "<escape> -") 'sp-splice-sexp)
(global-set-key (kbd "<escape> a") 'sp-beginning-of-sexp)
(global-set-key (kbd "<escape> e") 'sp-end-of-sexp)
(global-set-key (kbd "<escape> z") 'repeat)
(global-set-key (kbd "<escape> \"") 'jj/insert-double-quotes)
(global-set-key (kbd "<escape> '") 'jj/insert-single-quotes)
(global-set-key (kbd "<escape> 6") 'jj/insert-upward-v-exponential)
(global-set-key (kbd "<escape> i") 'jj/insert-upward-v-exponential)
(global-set-key (kbd "C-v") 'evil-scroll-down)
(global-set-key (kbd "M-v") 'evil-scroll-up)
(global-set-key (kbd "<escape> C-v") 'evil-scroll-page-down)
(global-set-key (kbd "<escape> M-v") 'evil-scroll-page-up)
(global-set-key (kbd "C-S-v") 'evil-scroll-page-down)
(global-set-key (kbd "M-V") 'evil-scroll-page-up)
(global-set-key (kbd "<C-S-s-down>") 'evil-scroll-line-down)
(global-set-key (kbd "<C-S-s-up>") 'evil-scroll-line-up)
(global-set-key (kbd "<S-s-down>") 'jj/evil-scroll-down-15-lines)
(global-set-key (kbd "<S-s-up>") 'jj/evil-scroll-up-15-lines)
(global-set-key (kbd "<s-down>") 'evil-scroll-line-down)
(global-set-key (kbd "<s-up>") 'evil-scroll-line-up)
(global-set-key (kbd "C-x C-s") nil)
(global-set-key (kbd "<escape> s") 'save-buffer)
(global-set-key (kbd "<escape> S") 'save-some-buffers)
(global-set-key (kbd "M-g M") 'manual-entry)
(global-set-key (kbd "M-s-m") 'iconify-or-deiconify-frame)
(global-set-key (kbd "<escape> <backspace>") 'jj/delete-backward-bracket-pair)
(global-set-key (kbd "<escape> C-d") 'jj/delete-forward-bracket-pairs)
(global-set-key (kbd "<escape> M-h") 'jj/delete-backward-bracket-pair)
(global-set-key (kbd "<escape> s-h") 'Helper-describe-bindings)

;; (define-key org-mode-map (kbd "<C-m>") 'exchange-point-and-mark)
;; unset C- and M- digit keys
;; set here because doesn't work in use-package (think because prefix defined by me)
(bind-key "o" #'poporg-dwim comment-map)
(bind-key "j" #'poporg-dwim comment-map)
(global-set-key (kbd "s-/ s-/") 'evilnc-comment-or-uncomment-lines)
(global-set-key (kbd "s-/ /") 'comment-or-uncomment-region)
(global-set-key (kbd "s-/ r") 'comment-or-uncomment-region)
(global-set-key (kbd "s-/ R") 'whole-line-or-region-uncomment-region)
(global-set-key (kbd "s-/ l") 'whole-line-or-region-comment-region)
(global-set-key (kbd "s-/ L") 'whole-line-or-region-uncomment-region)
(global-set-key (kbd "s-/ s") 'jj/comment-or-uncomment-sexp)
(global-set-key (kbd "s-/ S") 'jj/uncomment-sexp)
(global-set-key (kbd "s-/ u") 'whole-line-or-region-uncomment-region)
(global-set-key (kbd "s-/ p") 'evilnc-comment-or-uncomment-paragraphs)
(global-set-key (kbd "s-/ g") 'evilnc-comment-or-uncomment-to-the-line)
(global-set-key (kbd "s-/ k") 'comment-kill)
(global-set-key (kbd "s-/ d") 'comment-dwim)
(global-set-key (kbd "s-/ b") 'comment-box)
;; ("s-/ j" . poporg-dwim)
;; ("s-/ o" . poporg-dwim)
(define-key lispy-mode-map (kbd "s-/ <return>") 'lispy-comment)
(define-key lispy-mode-map (kbd "s-/ ;") 'lispy-comment)
(global-set-key (kbd "C-x C-;") 'evilnc-comment-or-uncomment-lines)

;; Match sublime bindings and s-maps
(global-set-key (kbd "M-t") 'jj/ivy-switch-buffer-use-virtual)
(global-set-key (kbd "s-b") 'ivy-switch-buffer)

;; PROJECTILE bindings
;; TODO: modify this or the noccur-dired function to directly take the hl-todo keywords regex
(global-set-key (kbd "H-p M-o") 'noccur-project)
(global-set-key (kbd "H-p H-o") 'noccur-project)

;;;;;;;;;; Counsel
(define-key commandpalette-map (kbd "s-e") 'turn-off-evil-mode)
(define-key commandpalette-map (kbd "s-P") 'counsel-M-x)
(define-key commandpalette-map (kbd "s-p") 'counsel-M-x)
(global-set-key (kbd "C-x B") 'jj/ivy-switch-buffer-use-virtual)
(define-key commandpalette-map (kbd "b") 'counsel-bookmark)
(define-key commandpalette-map (kbd "B") 'counsel-bookmarked-directory)
(define-key commandpalette-map (kbd "d") 'counsel-bookmarked-directory)
(define-key commandpalette-map (kbd "P") 'winner-undo)
;; (define-key commandpalette-map (kbd "p") 'winner-undo)
(define-key commandpalette-map (kbd "N") 'winner-redo)
(define-key commandpalette-map (kbd "n") 'winner-redo)
(define-key commandpalette-map (kbd "g a") 'counsel-ag)
(define-key commandpalette-map (kbd "g p") 'counsel-pt)
(define-key commandpalette-map (kbd "g r") 'counsel-rg)
(define-key commandpalette-map (kbd "a") 'counsel-rg)
(define-key commandpalette-map (kbd "g f") 'counsel-git)
(define-key commandpalette-map (kbd "g g") 'counsel-git-grep)
(define-key commandpalette-map (kbd "g o") 'ivy-org-jump-to-open-headline)
(global-set-key (kbd "C-c C-S-j") 'ivy-org-jump-to-open-headline)
(define-key commandpalette-map (kbd "r") 'counsel-recentf)
(define-key commandpalette-map (kbd "l") 'jj/emacs-lock-mode)
(define-key commandpalette-map (kbd "L") 'jj/emacs-lock-mode-all)
(define-key commandpalette-map (kbd "i") 'ivy-resume)
(define-key global-map (kbd "C-S-t") 'jj/find-open-last-killed-file)
(define-key global-map (kbd "s-T") 'jj/find-open-last-killed-file)
(define-key commandpalette-map (kbd "C-q") 'jj/toggle-window-dedicated)
(global-set-key (kbd "M-g M-d") 'dumb-jump-go)
(global-set-key (kbd "M-g M-b") 'dumb-jump-back)
(define-key commandpalette-map (kbd "v") 'jj/visible-mark-mode-enable)
(define-key commandpalette-map (kbd "s-v") 'jj/visible-mark-mode-enable)
(define-key commandpalette-map (kbd "V") 'jj/global-visible-mark-mode-enable)

;; Dumb jump map bindings
(define-key dumb-jump-map (kbd "j") 'dumb-jump-go)
(define-key dumb-jump-map (kbd "i") 'dumb-jump-go-prompt)
(define-key dumb-jump-map (kbd "l") 'dumb-jump-quick-look)
(define-key dumb-jump-map (kbd "o") 'dumb-jump-go-other-window)
(define-key dumb-jump-map (kbd "c") 'dumb-jump-go-current-window)
(define-key dumb-jump-map (kbd "b") 'dumb-jump-back)
(define-key dumb-jump-map (kbd "p") 'dumb-jump-back)
(define-key dumb-jump-map (kbd "x") 'dumb-jump-go-prefer-external)
(define-key dumb-jump-map (kbd "z") 'dumb-jump-go-prefer-external-other-window)
;; Tags and Gtags and Xref jump to definitions bindings
(global-set-key  (kbd "M-.") 'xref-find-definitions)
(global-set-key  (kbd "M-g .") 'helm-gtags-dwim)
(global-set-key  (kbd "M-g C-j") 'helm-gtags-select)
(global-set-key  (kbd "M-g j") 'helm-gtags-select)
(global-set-key  (kbd "M-g M-,") 'helm-gtags-show-stack)
(global-set-key  (kbd "M-g ,") 'helm-gtags-pop-stack)
(global-set-key  (kbd "M-g b") 'helm-gtags-previous-history)
(global-set-key  (kbd "M-g f") 'helm-gtags-next-history)
(global-set-key  (kbd "M-g M-.") 'ggtags-find-tag-dwim)
(define-key tags-jump-map  (kbd "g") 'counsel-gtags-dwim)
(define-key tags-jump-map  (kbd "t") 'counsel-gtags-dwim)
(define-key tags-jump-map  (kbd "r") 'counsel-gtags-find-reference)
(define-key tags-jump-map  (kbd "r") 'counsel-gtags-find-reference)
(define-key tags-jump-map  (kbd "o") 'helm-gtags-find-tag-other-window)
(define-key tags-jump-map  (kbd "i") 'helm-gtags-tags-in-this-function)
(define-key tags-jump-map  (kbd "j") 'helm-gtags-select)
(define-key tags-jump-map  (kbd "c") 'helm-gtags-create-tags)
(define-key tags-jump-map  (kbd "u") 'helm-gtags-update-tags)
(define-key tags-jump-map  (kbd "U") 'ggtags-update-tags)
(define-key tags-jump-map  (kbd "d") 'counsel-gtags-find-definition)
(define-key tags-jump-map  (kbd "s") 'counsel-gtags-find-symbol)
(define-key tags-jump-map  (kbd "b") 'counsel-gtags-go-backward)
(define-key tags-jump-map  (kbd "f") 'counsel-gtags-go-forward)

;; Window bindings
(define-prefix-command 'cp-window-map)
(define-key commandpalette-map (kbd "w") 'cp-window-map)
(define-key commandpalette-map (kbd "w l") 'jj/toggle-window-dedicated)
(define-key commandpalette-map (kbd "w K") 'jj/other-window-kill-buffer)
(define-key commandpalette-map (kbd "w q") 'jj/quit-help-windows)
(define-key commandpalette-map (kbd "w 1") 'delete-other-windows)
(define-key commandpalette-map (kbd "2") 'jj/split-window-below-and-balance)
(define-key commandpalette-map (kbd "3") 'jj/split-window-right-and-balance)
(define-key commandpalette-map (kbd "w 2") 'jj/split-window-vertically)
(define-key commandpalette-map (kbd "w b") 'balance-windows)
(define-key commandpalette-map (kbd "w 3") 'jj/split-window-horizontally)
(define-key commandpalette-map (kbd "w 4") 'jj/split-window-4)
(define-key commandpalette-map (kbd "w p") 'winner-undo)
(define-key commandpalette-map (kbd "w n") 'winner-redo)
(define-key commandpalette-map (kbd "w o") 'ivy-switch-buffer-other-window)
(define-key commandpalette-map (kbd "o") 'ivy-switch-buffer-other-window)
(define-key commandpalette-map (kbd "w t") 'jj/window-split-toggle-horizontal-vertical)
(define-key commandpalette-map (kbd "w d") 'delete-window)
(define-key commandpalette-map (kbd "0") 'delete-window)
(define-key commandpalette-map (kbd "-") 'ace-delete-window)
(define-key commandpalette-map (kbd "9") 'ace-delete-window)
;; also done with two C-u's into ace-window
(define-key commandpalette-map (kbd "w D") 'ace-delete-window)
(define-key commandpalette-map (kbd "D") 'ace-delete-window)
(define-key commandpalette-map (kbd "q") 'ace-delete-window)
(define-key commandpalette-map (kbd "C-q") 'ace-delete-window)
;; also done with one C-u into ace-window
(define-key commandpalette-map (kbd "w s") 'ace-swap-window)
(define-key commandpalette-map (kbd "w c") 'jj/visual-fill-column-center-text-toggle)
(define-key commandpalette-map (kbd "w s-w") 'delete-frame)
(define-key commandpalette-map (kbd "w s-k") 'delete-frame)
(define-key commandpalette-map (kbd "w s-d") 'delete-frame)
(define-key commandpalette-map (kbd "w s-n") 'make-frame)
(define-key commandpalette-map (kbd "w s-c") 'make-frame)
(define-key commandpalette-map (kbd "k") 'kill-current-buffer)
(define-key commandpalette-map (kbd "K") 'jj/kill-protected-buffer)
(global-set-key (kbd "C-x w") 'delete-window)
;; (global-set-key (kbd "C-x W") 'delete-other-windows)
(global-set-key (kbd "C-x o") 'ace-window)
(define-key commandpalette-map (kbd "w v") 'flip-frame)
(define-key commandpalette-map (kbd "w h") 'flop-frame)
(define-key commandpalette-map (kbd "w u") 'winner-undo)
(define-key commandpalette-map (kbd "w r") 'winner-redo)
(define-prefix-command 'cp-window-transpose-map)
(define-key commandpalette-map (kbd "w f") 'cp-window-transpose-map)
(define-key commandpalette-map (kbd "w f t") 'transpose-frame)
(define-key commandpalette-map (kbd "w f v") 'flip-frame)
(define-key commandpalette-map (kbd "w f d") 'delete-frame)
(define-key commandpalette-map (kbd "w f c") 'make-frame)
(define-key commandpalette-map (kbd "w f 2") 'flip-frame)
(define-key commandpalette-map (kbd "w f h") 'flop-frame)
(define-key commandpalette-map (kbd "w f r") 'rotate-frame)
(global-set-key (kbd "C-x K") 'jj/other-window-kill-buffer)
(global-set-key (kbd "C-c q") 'jj/quit-help-windows)
(global-set-key (kbd "C-x 4 t") 'jj/window-split-toggle-horizontal-vertical)
					; Set same binding as in sublime to take emacs full screen c-x 1
(global-set-key (kbd "M-s-<return>") 'jj/delete-other-windows-or-winner-undo-max-pane)
(global-set-key (kbd "C-M-s-<return>") 'jj/delete-other-windows-switch-other-buffer)
;; necessary to recognize the j and k keys correctly on emacs 26.1
(global-set-key (kbd "<C-s-268632074>") 'previous-multiframe-window)
(global-set-key (kbd "<C-s-268632075>") 'next-multiframe-window)
(global-set-key (kbd "C-s-j") 'previous-multiframe-window)
(global-set-key (kbd "C-s-k") 'next-multiframe-window)
(global-set-key (kbd "s-'") 'ace-window)
(global-set-key (kbd "C-M-s-6") 'make-frame)

(define-prefix-command 'cp-select-map)
(define-key commandpalette-map (kbd "s") 'cp-select-map)
(define-key commandpalette-map (kbd "s p") 'mark-paragraph)

;; Input method and key binding configuration.
(global-set-key (kbd "M-s M-s") 'jj/swiper-symbol-at-point)
(global-set-key (kbd "M-s s") 'jj/counsel-grep-or-swiper-symbol-at-point)
;; (global-set-key (kbd "M-s M-.") 'jj/swiper-symbol-at-point)
(global-set-key (kbd "M-s w") 'jj/counsel-grep-or-swiper-word-at-point)
(global-set-key (kbd "M-s j") 'jj/counsel-grep-or-swiper-region)
(global-set-key (kbd "M-s M-w") 'jj/swiper-word-at-point)
(global-set-key (kbd "M-s M-e") 'eww-search-words)
(global-set-key (kbd "M-s M-m") 'manual-entry)
(global-set-key (kbd "M-s a") 'swiper-all)
;; Uses visueal regex steroids but for regular use vr/select-replace to select the engine
(global-set-key (kbd "M-s c") 'vr/mc-mark)
(global-set-key (kbd "M-s r") 'vr/replace)
(global-set-key (kbd "M-s q") 'vr/query-replace)
(global-set-key (kbd "C-M-s") 'vr/isearch-forward)
(global-set-key (kbd "C-M-r") 'vr/isearch-backward)
(global-set-key (kbd "C-r") 'jj/swiper-region)
;; (global-set-key (kbd "C-s") 'jj/counsel-grep-or-swiper-region)
(global-set-key (kbd "C-c s") 'swiper-all)
(define-key swiper-map (kbd "M-s-å") 'swiper-mc)
(define-key ivy-minibuffer-map (kbd "M-y") 'ivy-next-line)
;; (define-key ivy-minibuffer-map (kbd "M-s m") 'ivy-restrict-to-matches)
(define-key ivy-minibuffer-map (kbd "C-r") 'ivy-previous-line)
(define-key ivy-minibuffer-map (kbd "C-r") 'ivy-previous-line)
(define-key ivy-minibuffer-map (kbd "C-d") 'delete-backward-char)
;; (define-key ivy-minibuffer-map (kbd "C-r") 'ivy-reverse-i-search)
(define-key ivy-minibuffer-map (kbd "C-w") 'whole-line-or-region-kill-region)
(define-key ivy-minibuffer-map (kbd "C-c <C-m>") 'ivy-call)

					;define-key commandpalette-map
(define-prefix-command 'ctrlz-map)
(global-set-key (kbd "C-z") 'ctrlz-map)
(define-key ctrlz-map (kbd "C-x") 'ace-jump-zap-to-char-dwim)
(define-key ctrlz-map (kbd "x") 'ace-jump-zap-to-char)
(define-key ctrlz-map (kbd "C-z") 'ace-jump-zap-up-to-char-dwim)
(define-key ctrlz-map (kbd "z") 'ace-jump-zap-up-to-char)
;; (global-set-key (kbd "C-z")  'ace-jump-zap-up-to-char-dwim)
(global-set-key (kbd "M-z")  'ace-jump-zap-to-char)
(global-set-key (kbd "M-Z")  'ace-jump-zap-up-to-char)
(global-set-key (kbd "M-\\")  'cycle-spacing)

;; Kill lines and words (currently set to delete except for kill line)
(global-set-key (kbd "<M-s-backspace>") 'kill-whole-line)
;; (global-set-key (kbd "C-S-k") 'jj/backward-kill-line) ; Ctrl+Shift+k
;; (global-set-key (kbd "M-d") 'kill-word)
;; (global-set-key (kbd "<M-backspace>") 'backward-kill-word)
;; Replace putting kill word and other things on the kill ring
;; (global-set-key (kbd "C-M-k") #'jj/forward-kill-sexp-or-dir)
;; (global-set-key (kbd "<C-M-backspace>") #'jj/backward-kill-sexp-or-dir)
;; (global-set-key (read-kbd-macro "<C-M-backspace>") 'backward-kill-sexp)
(global-set-key (kbd "<C-M-s-268632075>") 'whole-line-or-region-kill-region)
(global-set-key (kbd "C-M-s-k") 'whole-line-or-region-kill-region)
(global-set-key (kbd "M-s-k") 'jj/delete-whole-line)
(global-set-key (kbd "M-s-˚") 'jj/delete-whole-line)
(global-set-key (kbd "C-w") 'whole-line-or-region-kill-region)
(define-key easy-kill-base-map (kbd "C-w") 'easy-kill-region)
(define-key easy-kill-base-map (kbd "k") 'easy-kill-region)
(define-key easy-kill-base-map (kbd "K") 'easy-kill-delete-region)
(define-key easy-kill-base-map (kbd "x") 'easy-kill-delete-region)
(define-key easy-kill-base-map (kbd "o") 'easy-kill-er-expand)
(define-key easy-kill-base-map (kbd "M-w") 'easy-kill-unhighlight)
(define-key easy-kill-base-map (kbd "j") 'easy-kill-unhighlight)
(define-key easy-kill-base-map (kbd "g") 'easy-kill-unhighlight)
(define-key easy-kill-base-map (kbd "n") 'easy-kill-thing)
(define-key easy-kill-base-map (kbd "C-M-w") 'easy-kill-append)
(define-key easy-kill-base-map (kbd "A") 'easy-kill-append)
(define-key easy-kill-base-map (kbd "i") 'easy-kill-er-unexpand)
(define-key easy-kill-base-map (kbd "<backspace>") 'easy-kill-delete-region)
(define-key easy-kill-base-map (kbd "m") 'easy-kill-mark-region)
(define-key easy-kill-base-map (kbd "<C-m>") 'easy-kill-mark-region)
(global-set-key (kbd "<C-M-s-backspace>") 'whole-line-or-region-kill-region)
(global-set-key (kbd "C-M-k") 'jj/delete-sexp)
(global-set-key (kbd "M-K") 'kill-sexp)
(global-set-key (kbd "<escape> C-k") 'jj/kill-line)
(global-set-key (kbd "M-k") 'kill-sentence)
;; (global-set-key (kbd "<escape> M-k") 'kill-sentence)
(global-set-key (kbd "<escape> M-w") 'jj/kill-line-save)
(global-set-key (kbd "<escape> w") 'jj/kill-line-save)
(global-set-key (kbd "<escape> l") 'jj/kill-line)
(global-set-key (kbd "<escape> k") 'sp-kill-sexp)
(global-set-key (kbd "<escape> d") (lambda () (interactive) (sp-kill-sexp '(16))))
(global-set-key (kbd "<escape> M-k") (lambda () (interactive) (sp-kill-sexp '(16))))
(global-set-key (kbd "<escape> C-M-d") (lambda () (interactive) (sp-kill-sexp '(16))))
(global-set-key (kbd "<escape> K") (lambda () (interactive) (sp-kill-sexp 0)))
(global-set-key (kbd "<escape> C-M-k") 'kill-sexp)
(global-set-key (kbd "<escape> M-d") 'kill-word)
(global-set-key (kbd "<escape> <C-M-backspace>") 'backward-kill-sexp)
(global-set-key (kbd "<escape> M-t") 'hl-todo-occur)
(global-set-key (kbd "<escape> M-n") 'hl-todo-next)
(global-set-key (kbd "<escape> M-p") 'hl-todo-previous)
(global-set-key (kbd "<escape> t") 'hl-todo-occur)
(global-set-key (kbd "<escape> T") 'hl-todo-insert-keyword)
(global-set-key (kbd "<C-s-backspace>") 'backward-kill-sexp)
(global-set-key (kbd "<escape> <C-backspace>") 'backward-kill-word)
(global-set-key (kbd "<escape> M-DEL") 'backward-kill-word)
(global-set-key (kbd "C-S-k") 'jj/delete-line) ; Ctrl+Shift+k
(global-set-key (read-kbd-macro "<s-backspace>") 'jj/delete-line-backward)
(global-set-key (read-kbd-macro "<escape> <s-backspace>") 'jj/kill-line-backward)
(global-set-key (kbd "M-d") 'jj/delete-word)
(global-set-key (kbd "<M-backspace>") 'jj/delete-backward-word)
;; (global-set-key (kbd "C-k") 'jj/delete-line)
(global-set-key (kbd "C-M-k") 'jj/delete-forward-sexp-or-dir)
(global-set-key (kbd "<C-M-backspace>") 'jj/delete-backward-sexp-or-dir)
(global-set-key (kbd "s-D") 'jj/duplicate-line-or-region)
(global-set-key (kbd "C-c d") 'jj/duplicate-line-or-region)

					; (global-set-key (read-kbd-macro "<C-x j>") 'ess/org-show-just-me)
(define-key org-mode-map (kbd "C-x n o") 'jj/org-show-just-me)
(define-key org-mode-map (kbd "C-x n <tab>") 'jj/org-show-just-me)
(define-key text-mode-map (kbd "M-+") 'count-words)
(define-key org-mode-map (kbd "M-e") 'forward-sentence)
(define-key org-mode-map (kbd "M-E") 'jj/org-next-item-at-ident)
(define-key org-mode-map (kbd "M-a") 'backward-sentence)
(define-key org-mode-map (kbd "M-A") 'jj/org-previous-item-at-ident)
(define-key org-mode-map (kbd "C-M-e") 'jj/org-next-item-at-ident)
(define-key org-mode-map (kbd "C-M-a") 'jj/org-previous-item-at-ident)
;; (define-key org-mode-map (kbd "M-}") 'jj/org-forward-element-at-ident)
;; (define-key org-mode-map (kbd "M-{") 'jj/org-backward-element-at-ident)
(define-key org-mode-map (kbd "M-}") 'org-forward-element)
(define-key org-mode-map (kbd "M-{") 'org-backward-element)
(define-key org-mode-map (kbd "C-c k") 'org-metaright)
(define-key org-mode-map (kbd "C-c K") 'org-metaleft)
(define-key org-mode-map (kbd "C-c b k") 'org-metaright)
(define-key org-mode-map (kbd "C-c b j") 'org-metaleft)
(define-key org-mode-map (kbd "C-c C-S-j") 'ivy-org-jump-to-open-headline)
(define-key org-mode-map (kbd "C-c C-j") 'ivy-org-jump-to-heading)
(define-key org-mode-map (kbd "C-c j") 'counsel-org-goto-all)
(define-key org-mode-map (kbd "C-c M-j") 'counsel-org-goto)
(define-key org-mode-map (kbd "C-c J") 'ivy-org-jump-to-heading-in-directory)
					;(define-key org-mode-map (kbd "C-c i") 'org-do-demote)
					;(define-key org-mode-map (kbd "C-c u") 'org-do-promote) 'org-indent-item 'org-outdent-item
;; (define-key org-mode-map (kbd "C-c i") 'org-shiftmetaright)
;; (define-key org-mode-map (kbd "C-c u") 'org-shiftmetaleft)
(define-key org-mode-map (kbd "C-c C-S-k") 'org-shiftmetaright)
(define-key org-mode-map (kbd "C-c C-S-j") 'org-shiftmetaleft)
(define-key org-mode-map (kbd "M-=") 'org-ctrl-c-minus)
(define-key org-mode-map (kbd "s-B") 'org-bold-region-or-point)
(define-key org-mode-map (kbd "s-I") 'org-italics-region-or-point)
(define-key org-mode-map (kbd "s-V") 'org-verbatim-region-or-point)
(define-key org-mode-map (kbd "s-C") 'org-code-region-or-point)
(define-key org-mode-map (kbd "<escape> ~") 'org-code-region-or-point)
(define-key org-mode-map (kbd "s-M") 'org-latex-math-region-or-point)
(define-key org-mode-map (kbd "C-c n") 'jj/org-move-headline-next-top-level)
(define-key org-mode-map (kbd "C-c m") 'jj/org-move-headline-next-second-level)
(define-key org-mode-map (kbd "C-c b b") 'jj/org-metaleft-next-line-previous-item)
(define-key org-mode-map (kbd "C-c b n") 'jj/org-metaleft-next-line-beginning-item)

(eval-after-load "latex"
  '(progn
     (define-key LaTeX-mode-map (kbd "M-e") 'forward-sentence)
     (define-key LaTeX-mode-map (kbd "M-a") 'backward-sentence)
     (define-key LaTeX-mode-map (kbd "C-c ~") 'jj/TeX-command-run-all-auto-save)
     (define-key LaTeX-mode-map (kbd "C-c b") 'jj/TeX-LaTeX-auctex-latexmk-compile-view)
     (define-key LaTeX-mode-map (kbd "C-c B") 'jj/TeX-LaTeX-auctex-xelatexmk-compile-view)
     (define-key LaTeX-mode-map (kbd "C-c s-b") 'jj/TeX-LaTeX-auctex-latexmk-compile-view)
     (define-key LaTeX-mode-map (kbd "<escape> B") 'jj/TeX-LaTeX-auctex-latexmk-compile-view)
     (define-key LaTeX-mode-map (kbd "<escape> C-b") 'jj/TeX-LaTeX-auctex-latexmk-compile-view)
     (define-key LaTeX-mode-map (kbd "<escape> C-B") 'jj/TeX-LaTeX-auctex-xelatexmk-compile-view)
     (define-key LaTeX-mode-map (kbd "<escape> s-b") 'jj/TeX-LaTeX-auctex-latexmk-compile-view)
     (define-key LaTeX-mode-map (kbd "C-c V") 'pdf-sync-forward-search)
     (define-key LaTeX-mode-map (kbd "<escape> V") 'pdf-sync-forward-search)
     (define-key LaTeX-mode-map (kbd "<escape> s-v") 'pdf-sync-forward-search)
     (define-key LaTeX-mode-map (kbd "C-c j") 'counsel-semantic-or-imenu)
     ))

;; Moved into orgtbl-mode-hook
;; (define-key org-mode-map (kbd S-TAB") 'org-table-previous-field)

(add-hook 'orgtbl-mode-hook
	  (lambda ()
	    (define-key orgtbl-mode-map (kbd "S-TAB") 'org-table-previous-field)
	    (define-key orgtbl-mode-map (kbd "M-C-n") 'org-table-next-field)
	    (define-key orgtbl-mode-map (kbd "M-C-p") 'org-table-previous-field)
	    ))

					; First is Old binding if ; not set to return
(global-set-key (kbd "C-;") 'dabbrev-expand)
(global-set-key (kbd "s-RET") 'dabbrev-expand)
(global-set-key (kbd "s-<return>") 'dabbrev-expand)
;; Possibly change later so j goes to a menu doing counsel commands
(define-key lisp-mode-map (kbd "C-c C-j") 'counsel-imenu)
(define-key lisp-mode-map (kbd "C-c j") 'lispy-goto)
(define-key emacs-lisp-mode-map (kbd "C-c C-j") 'counsel-imenu)
(define-key emacs-lisp-mode-map (kbd "C-c j") 'lispy-goto)
(define-key python-mode-map (kbd "C-c C-j") 'counsel-imenu)
(define-key python-mode-map (kbd "C-c j") 'counsel-semantic-or-imenu)
(global-set-key (kbd "C-x C-r") 'jj/find-alternative-file-with-sudo)

(global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
(global-set-key (kbd "C-S-s-e") 'mc/edit-lines)
(global-set-key (kbd "C-S-s-n") 'mc/mark-next-like-this)
(global-set-key (kbd "C-S-s-p") 'mc/mark-previous-like-this)
(define-key mc/keymap (kbd "<return>") nil)
(define-key mc/keymap (kbd "C-S-s-l") 'mc/unmark-next-like-this)
(define-key mc/keymap (kbd "C-S-s-h") 'mc/unmark-previous-like-this)
(define-key mc/keymap (kbd "C-S-s-j") 'mc/skip-to-previous-like-this)
(define-key mc/keymap (kbd "C-S-s-k") 'mc/skip-to-next-like-this)
(global-unset-key (kbd "C-S-<down-mouse-1>"))
(global-set-key (kbd "C-S-<mouse-1>") 'mc/add-cursor-on-click)
;; Could make this to be a local key map
(global-set-key (kbd "M-s-a") 'mc/mark-all-like-this)
(global-set-key (kbd "M-s-å") 'mc/mark-all-like-this)
(global-set-key (kbd "C-x r 1") 'gse-number-rectangle)
;; Backup commands
(define-key mc/keymap (kbd "M-s M-n") 'mc/insert-numbers)
(define-key mc/keymap (kbd "M-s M-l") 'mc/insert-letters)
;; (define-key mc/keymap (kbd "m-s m-d") 'mc/mark-next-like-this)
;; (define-key mc/keymap (kbd "m-s m-d") 'mc/mark-next-like-this)
;; (define-key mc/keymap (kbd "m-s m-r") 'mc/mark-previous-like-this)
;; (define-key mc/keymap (kbd "m-s m-n") 'mc/unmark-next-like-this)
;; (define-key mc/keymap (kbd "m-s m-p") 'mc/unmark-previous-like-this)
;; (define-key mc/keymap (kbd "M-s M-s") 'mc/skip-to-next-like-this)

(global-set-key (kbd "S-s-SPC") 'er/expand-region)
(global-set-key (kbd "s-+") 'er/expand-region)
(global-set-key (kbd "s-_") 'er/contract-region)
(global-set-key (kbd "s-)") (lambda () (interactive) (er/expand-region 0)))


;; Setup copy and paste for s-c and s-v
(define-key org-mode-map (kbd "s-v") 'org-yank)
(global-set-key (kbd "s-v") 'yank)
(global-set-key (kbd "s-c") 'kill-ring-save)

(setq bmkp-jump-map-prefix-keys (list (kbd "s-p j")))
(setq bmkp-bookmark-map-prefix-keys (list (kbd "s-p p")))
(setq bmkp-jump-other-window-map-prefix-keys (list (kbd "s-p 4 j")))
;; (bmkp-set-map-prefix-key 'bmkp-jump-map-prefix-keys (list (kbd "s-p j")))
;; For avy which is similar to ace-jump
(define-prefix-command 'avy-jump-map)
(global-set-key (kbd "C-x j") 'avy-jump-map)
(global-set-key (kbd "C-x j l") 'avy-goto-line)
(global-set-key (kbd "C-x j p") 'avy-jump-to-paragraph)
(global-set-key (kbd "C-x j s") 'avy-jump-to-sentence)
(global-set-key (kbd "C-x j w") 'avy-jump-to-word-in-line)
(global-set-key (kbd "C-x j C-a") 'avy-goto-line)
(global-set-key (kbd "C-x j e") 'avy-goto-end-of-line)
(global-set-key (kbd "C-x j c") 'avy-goto-word-1)
(global-set-key (kbd "C-x j 2") 'avy-goto-char-2)
(global-set-key (kbd "C-x j C-e") 'avy-goto-end-of-line)
(global-set-key (kbd "C-x j t") 'avy-goto-char-timer)
(global-set-key (kbd "s-.") 'avy-goto-char-timer)
(define-key org-mode-map (kbd "C-x j h") 'ivy-org-jump-to-visible-headline)
(define-key org-mode-map (kbd "s-,") 'ivy-org-jump-to-visible-headline)
;; expand region overwrites the below hot key so added
(define-key org-mode-map (kbd "C-c g") 'org-mark-ring-goto)
(define-key org-mode-map (kbd "<C-M-return>") 'org-insert-heading-respect-content)
(define-key org-mode-map (kbd "<C-s-return>") 'org-insert-heading-after-current)
(define-key org-mode-map (kbd "<escape> <C-M-return>") 'jj/org-insert-heading-respect-content-and-delete-current-line)
(define-key org-mode-map (kbd "<escape> t") 'jj/org-show-todo-tree-then-remove-occur-highlights)
(define-key org-mode-map (kbd "<escape> o") 'org-occur)
(define-key org-mode-map (kbd "<escape> O") 'org-remove-occur-highlights)
(define-key org-mode-map (kbd "C-c C-g") 'org-mark-ring-goto)(define-prefix-command 'dired-h-prefix-map)
(define-key dired-mode-map (kbd "h") 'dired-h-prefix-map)
(define-key dired-h-prefix-map (kbd "P") 'jj/dired-up-directory-follow-symlink-up)
(define-key dired-h-prefix-map (kbd "^") 'jj/dired-up-directory-follow-symlink-up)
;; (define-key dired-h-prefix-map (kbd "p") 'jj/dired-up-directory-follow-symlink-up)
(define-key dired-h-prefix-map (kbd "f") 'jj/dired-find-file-following-symlinks)
(define-key dired-h-prefix-map (kbd "a") 'jj/dired-find-alternate-file-following-symlinks)
(define-key dired-h-prefix-map (kbd "]") 'jj/dired-find-alternate-file-following-symlinks)
(define-key dired-h-prefix-map (kbd "v") 'jj/dired-view-file-following-symlinks)
(define-key dired-h-prefix-map (kbd "r") 'jj/dired-sort-toggle-reverse-switch)
(define-key dired-h-prefix-map (kbd "w") 'jj/dired-sort-add-classify-switch)
(define-key dired-h-prefix-map (kbd "W") 'jj/dired-sort-remove-classify-switch)
(define-key dired-h-prefix-map (kbd "s") 'jj/dired-cycle-switches)
(define-key dired-h-prefix-map (kbd "S") 'jj/dired-sort-by-size-switch-toggle)
(define-key dired-h-prefix-map (kbd "c") 'jj/dired-sort-choose)
(define-key dired-h-prefix-map (kbd "C") 'jj/dired-version-file)
(define-key dired-h-prefix-map (kbd ",") 'beginning-of-buffer)
(define-key dired-h-prefix-map (kbd ".") 'end-of-buffer)
(define-key dired-h-prefix-map (kbd "p") 'peep-dired)
(define-key dired-h-prefix-map (kbd "m") 'dired-do-chmod)
(define-key dired-h-prefix-map (kbd "H") 'dired-do-hardlink)
(define-key dired-h-prefix-map (kbd "t") 'jj/dired-sort-by-time-switch-toggle)
(define-key dired-h-prefix-map (kbd "RET") 'jj/dired-advertised-find-file-following-symlinks)

(define-prefix-command 'dired-question-prefix-map)
(define-key dired-mode-map (kbd "1") 'beginning-of-buffer)
(define-key dired-mode-map (kbd "2") 'end-of-buffer)
(define-key dired-mode-map (kbd "3") 'jj/dired-beginning-of-subdir)
(define-key dired-mode-map (kbd "C-M-n") 'jj/dired-next-subdir)
(define-key dired-mode-map (kbd "C-M-p") 'jj/dired-prev-subdir)
(define-key dired-mode-map (kbd "M-N") 'jj/dired-next-subdir)
(define-key dired-mode-map (kbd "M-P") 'jj/dired-prev-subdir)
(define-key dired-mode-map (kbd "C-M-u") 'jj/dired-tree-up)
(define-key dired-mode-map (kbd "C-M-d") 'jj/dired-tree-down)
(define-key dired-mode-map (kbd "M-#") 'jj/dired-hide-all-but-this-dir)
(define-key dired-mode-map (kbd "?") 'dired-question-prefix-map)
(define-key dired-mode-map (kbd "_") 'jj/dired-rename-space-to-underscore)
;; (define-key dired-mode-map (kbd "-") 'jj/dired-rename-space-to-hyphen)
(define-key dired-mode-map (kbd "<escape> -") 'jj/dired-rename-space-to-hyphen)
(define-key dired-mode-map (kbd "Q") 'jj/quit-window-kill)
(define-key help-mode-map (kbd "Q") 'jj/quit-window-kill)
(define-key image-mode-map (kbd "Q") 'jj/quit-window-kill)
(define-key dired-mode-map (kbd "X") 'dired-do-async-shell-command)
(define-key dired-mode-map (kbd "r") 'dired-toggle-read-only)
(define-key dired-mode-map (kbd "9") 'jj/dired-rename-hyphen-to-underscore)
(define-key dired-mode-map (kbd "0") 'jj/dired-rename-underscore-to-hyphen)
(define-key dired-mode-map (kbd "8") 'jj/dired-rename-hyphen-or-underscore-to-space)
(define-key dired-mode-map (kbd "C-S-SPC") 'jj/dired-rename-hyphen-or-underscore-to-space)

(define-key dired-question-prefix-map (kbd "?") 'dired-summary)

(define-key dired-mode-map (kbd "C-c M-o") 'dired-omit-switch)
(define-key dired-mode-map (kbd "C-c m") 'dired-do-chmod)
(define-key dired-mode-map (kbd "H") 'dired-do-chmod)
(define-key dired-mode-map (kbd "h o") 'dired-omit-switch)
(define-key dired-mode-map (kbd "h O") 'noccur-dired)
(global-set-key (kbd "C-c t") 'jj/open-iterm-terminal-here)
;; (add-hook 'dired-mode-hook (lambda () (dired-omit-mode 1)))

(eval-after-load "wdired"
  '(progn
     (define-key wdired-mode-map (kbd "<escape> C-g") 'wdired-abort-changes)
     ))


(define-prefix-command 'jj-flyspell-mode-map)
(global-set-key (kbd "M-s f") 'jj-flyspell-mode-map)
(eval-after-load "flyspell"
  '(progn
     (define-key flyspell-mode-map (kbd "s-RET") 'dabbrev-expand)
     ;; (define-key flyspell-mode-map (kbd "M-p") 'flyspell-auto-correct-previous-word)
     (define-key flyspell-mode-map (kbd "C-.") 'flyspell-auto-correct-previous-word)
     (define-key flyspell-mode-map (kbd "C-M-i") 'flyspell-auto-correct-word)
     (define-key flyspell-mode-map (kbd "M-s f a") 'jj/ispell-append-current-and-sort)
     (define-key flyspell-mode-map (kbd "M-s f w") 'ispell-word)
     (define-key flyspell-mode-map (kbd "M-s f i") 'ispell-word)
     (define-key flyspell-mode-map (kbd "M-s f p") 'flyspell-auto-correct-previous-word)
     (define-key flyspell-mode-map (kbd "M-s f f") 'flyspell-correct-previous-word-generic)
     ))

;; Archive-mode is arc-mode
(eval-after-load "arc-mode"
  '(progn
     (define-key archive-mode-map (kbd "U") 'archive-unmark-all-files)
     (define-key archive-mode-map (kbd "<M-backspace>") 'archive-unmark-all-files)))

(eval-after-load "elpy"
  '(progn
     (define-key elpy-mode-map (kbd "C-c C-c") 'elpy-shell-send-region-or-buffer)
     ))

(eval-after-load "dired+"
  '(progn
     ;; Think this can be replaced with browse-url-of-dired-file
     ;; (define-key dired-mode-map (kbd "z") 'browse-url-of-dired-file)
     (define-key dired-mode-map (kbd "z")
       (lambda () (interactive)
	 (let ((fn (dired-get-file-for-visit)))
	   (start-process "default-app" nil "open" fn))))
     (define-key dired-mode-map (kbd "V")
       (lambda () (interactive)
	 (let ((fn (dired-get-file-for-visit)))
	   (start-process "default-app" nil "open" "-g" fn))))
     (define-key dired-mode-map (kbd "h z") 'diredp-compress-this-file)
     (define-key dired-mode-map (kbd "C-c C-o") 'jj/show-in-path-finder)
     (define-key dired-mode-map (kbd "P") 'dired-up-directory)
     (define-key dired-mode-map (kbd "<M-backspace>") 'dired-unmark-all-files)
     (define-key dired-mode-map (kbd "N") 'dired-view-file)
     (define-key dired-mode-map (kbd "U") 'dired-unmark-all-marks)
     (define-key dired-mode-map (kbd "[") 'jj/dired-go-up-directory-same-buffer)
     (define-key dired-mode-map (kbd "]") 'dired-find-alternate-file)
     (define-key dired-mode-map (kbd "RET") 'dired-advertised-find-file)
     (define-key dired-mode-map (kbd "C-M-s-4") 'dired-kill-subdir)
     (define-key dired-mode-map (kbd "'") 'jj/dired-kill-subdir)
     (define-key dired-mode-map (kbd "\"") 'jj/dired-kill-tree)
     (define-key dired-mode-map (kbd "_") 'jj/dired-rename-space-to-underscore)
     (define-key dired-mode-map (kbd "-") 'scimax-dired-cycle-space-hyphen-underscore)
     (define-key dired-mode-map (kbd "c") 'jj/dired-create-file)
     (define-key dired-mode-map (kbd "K") 'jj/dired-kill-subdir-pop-mark)
     (define-key dired-mode-map (kbd "e") 'jj/counsel-find-name-everything)
     ;; if you are using ido,you'd better disable ido for dired
     ;; (define-key (cdr ido-minor-mode-map-entry) [remap dired] nil) ;in ido-setup-hook
     ;; Possibly change this to counsel-bookmark
     (define-key dired-mode-map "b" 'counsel-bookmarked-directory)
     (define-key dired-mode-map "B" 'counsel-bookmark)
     (define-key dired-mode-map "<" 'dired)
     (define-key dired-mode-map (kbd "w") 'dired-ranger-copy)
     (define-key dired-mode-map (kbd "W") 'dired-copy-filename-as-kill)
     (define-key dired-mode-map (kbd "E") 'dired-ranger-move)
     (define-key dired-mode-map (kbd "/ t") 'dired-filter-mode)
     (define-key dired-mode-map (kbd "M") 'dired-ranger-move)
     ;; Originally dired-do-chmod mapped to M
     ;; (define-key dired-mode-map (kbd "M") 'dired-do-chmod)
     (define-key dired-mode-map (kbd "Y") 'dired-ranger-paste)
     (defvar dired-narrow-filter-map
       (let ((map (make-sparse-keymap)))
	 (define-key map "," 'dired-narrow)
	 (define-key map "r" 'dired-narrow-regexp)
	 (define-key map "f" 'dired-narrow-fuzzy)
	 map)
       "Keymap used for filtering files.")
     (define-key dired-mode-map (kbd ",") dired-narrow-filter-map)

     ))
(defvar grep-and-find-map (make-sparse-keymap))
(define-key global-map "\C-xf" grep-and-find-map)
;; (define-key global-map "\C-xfg" 'find-grep-dired)
;; (define-key global-map "\C-xfn" 'find-name-dired)
(define-key global-map "\C-xff" 'jj/counsel-find-name-everything)
(define-key global-map "\C-xfe" 'jj/counsel-find-name-everything)
;; (define-key global-map "\C-xfd" 'find-dired)
(define-key global-map (kbd "\C-xfa") 'counsel-ag)
(define-key global-map (kbd "\C-xfp") 'counsel-pt)
(define-key global-map (kbd "\C-xfr") 'counsel-rg)
(define-key global-map (kbd "\C-xf\C-r") 'jj/find-file-root)
(define-key global-map (kbd "\C-xfr") 'counsel-rg)
(define-key global-map (kbd "\C-xfh") 'counsel-git)
(define-key global-map (kbd "\C-xfg") 'counsel-git-grep)
(define-key global-map (kbd "\C-xf\C-f") 'counsel-git)
(define-key global-map (kbd "\C-xf\C-g") 'counsel-git-grep)
(define-key global-map (kbd "\C-xfo") 'ivy-org-jump-to-open-headline)
(define-key global-map "\C-xg" 'magit-status)
;; (define-key global-map "\C-xg" 'jj/counsel-find-name-everything)

(global-set-key (kbd "C-x C-d") 'jj/ivy-dired-recent-dirs)
(global-set-key (kbd "C-x s-d") 'list-directory)

(global-set-key (kbd "C-s-<tab>") 'jj/switch-to-previous-buffer)
(global-set-key (kbd "<escape> <tab>") 'jj/switch-to-previous-buffer)
(global-set-key (kbd "C-S-<tab>") 'jj/switch-to-previous-buffer)

(define-key process-menu-mode-map (kbd "C-k") 'jj/delete-kill-process-at-point)

(global-set-key (kbd "C-M-s-9") 'jj/goto-last-change)
;; (global-set-key (kbd "M-[")  'nice-jumper/backward)
;; (global-set-key (kbd "M-]") 'nice-jumper/forward)
(global-set-key (kbd "C-(") 'back-button-global-backward)
(global-set-key (kbd "C-)") 'back-button-global-forward)
(global-set-key (kbd "s-[") 'back-button-local-backward)
(global-set-key (kbd "s-]") 'back-button-local-forward)

(global-set-key [remap kill-ring-save] 'easy-kill)
(global-set-key [remap mark-sexp] 'easy-mark)
(global-set-key (kbd "M-@") 'easy-mark)

(define-key google-this-mode-submap "T" #'jj/google-this-background)
(define-key google-this-mode-submap "N" #'jj/google-this-noconfirm-background)
(define-key google-this-mode-submap "b" #'jj/google-this-noconfirm-background)
(define-key google-this-mode-submap "W" #'jj/google-this-word-background)
(define-key google-this-mode-submap "F" #'jj/google-this-forecast-background)

;; (global-set-key (kbd "M-1") 'jj-eyebrowse-map)
;; (global-set-key (kbd "M-1") 'jj-eyebrowse-map)

(define-key jj-eyebrowse-map (kbd "C")	'wg-create-workgroup)
(define-key jj-eyebrowse-map (kbd "Y")	'wg-clone-workgroup)
(define-key jj-eyebrowse-map (kbd "R")	'wg-rename-workgroup)
(define-key jj-eyebrowse-map (kbd "M")	'jj/wg-workgroups-mode-switch)
(define-key jj-eyebrowse-map (kbd "A")	'jj/wg-workgroups-mode-switch)
(define-key jj-eyebrowse-map (kbd "B")	'wg-switch-to-workgroup)
(define-key jj-eyebrowse-map (kbd "K")	'wg-kill-workgroup)
(define-key jj-eyebrowse-map (kbd "S")	'wg-switch-to-workgroup)
(define-key jj-eyebrowse-map (kbd "P")	'wg-switch-to-previous-workgroup)
(define-key jj-eyebrowse-map (kbd "<")	'wg-switch-to-workgroup-left)
(define-key jj-eyebrowse-map (kbd ">")	'wg-switch-to-workgroup-right)
(define-key jj-eyebrowse-map (kbd "C-d")	'desktop-change-dir)
(define-key jj-eyebrowse-map (kbd "C-k")	'desktop-clear)
(define-key jj-eyebrowse-map (kbd "C-K")	'desktop-remove)
(define-key jj-eyebrowse-map (kbd "C-l")	'desktop-lazy-complete)
(define-key jj-eyebrowse-map (kbd "C-f")	'desktop-read)
(define-key jj-eyebrowse-map (kbd "C-s")	'desktop-save-in-desktop-dir)
(define-key jj-eyebrowse-map (kbd "s-s")	'desktop-save)
(define-key jj-eyebrowse-map (kbd "C-c")	'desktop-save)

(define-key image-mode-map (kbd "=")	'image-increase-size)
(define-key image-mode-map (kbd "_")	'image-decrease-size)
(define-key pdf-view-mode-map (kbd "_")	'pdf-view-shrink)
;; (define-prefix-command 'pdf-view-mode-synctex-map)
;; (define-key pdf-view-mode-map (kbd "j") 'pdf-view-mode-synctex-map)
;; (define-key pdf-view-mode-synctex-map (kbd "j")	'pdf-isearch-sync-backward)
(define-key pdf-view-mode-map (kbd "j")	'pdf-isearch-sync-backward)

(global-set-key (kbd "s-h 0") 'xah-lookup-word-thesaurus)
(global-set-key (kbd "s-h )") 'xah-lookup-word-thesaurus-eww)
(global-set-key (kbd "s-h -") 'xah-lookup-word-power-thesaurus)
(global-set-key (kbd "s-h _") 'xah-lookup-word-power-thesaurus-eww)
(global-set-key (kbd "s-h 9") 'xah-lookup-word-definition)
(global-set-key (kbd "s-h (") 'xah-lookup-word-definition-eww)
(global-set-key (kbd "s-h 8") 'xah-lookup-word-dict-org)

(eval-after-load "magit-mode"
  '(progn
     (define-key magit-mode-map (kbd "Q") 'jj/magit-mode-kill-buffer)
     (eval-after-load "magit-section"
       '(progn
	  (define-key magit-mode-map (kbd "M-1") nil)
	  (define-key magit-mode-map (kbd "M-2") nil)
	  (define-key magit-mode-map (kbd "M-3") nil)
	  (define-key magit-mode-map (kbd "M-4") nil)
	  (define-key magit-mode-map (kbd "M-5") nil)
	  (define-key magit-mode-map (kbd "M-s-1") 'magit-section-show-level-1-all)
	  (define-key magit-mode-map (kbd "M-s-2") 'magit-section-show-level-2-all)
	  (define-key magit-mode-map (kbd "M-s-3") 'magit-section-show-level-3-all)
	  (define-key magit-mode-map (kbd "M-s-4") 'magit-section-show-level-4-all)
	  (define-key magit-mode-map (kbd "M-s-5") 'magit-section-show-level-5-all)
	  ))))

(eval-after-load "magit-mode"
  '(progn
     (define-key magit-mode-map (kbd "Q") 'jj/magit-mode-kill-buffer)
     (eval-after-load "magit-section"
       '(progn
	  (define-key magit-mode-map (kbd "M-1") nil)
	  (define-key magit-mode-map (kbd "M-2") nil)
	  (define-key magit-mode-map (kbd "M-3") nil)
	  (define-key magit-mode-map (kbd "M-4") nil)
	  (define-key magit-mode-map (kbd "M-5") nil)
	  (define-key magit-mode-map (kbd "M-s-1") 'magit-section-show-level-1-all)
	  (define-key magit-mode-map (kbd "M-s-2") 'magit-section-show-level-2-all)
	  (define-key magit-mode-map (kbd "M-s-3") 'magit-section-show-level-3-all)
	  (define-key magit-mode-map (kbd "M-s-4") 'magit-section-show-level-4-all)
	  (define-key magit-mode-map (kbd "M-s-5") 'magit-section-show-level-5-all)
	  ))))

(eval-after-load "simple"
  '(progn
     (bind-key "1" #'beginning-of-buffer messages-buffer-mode-map)
     (bind-key "2" #'end-of-buffer messages-buffer-mode-map)
     (bind-key "n" #'next-line messages-buffer-mode-map)
     (bind-key "p" #'previous-line messages-buffer-mode-map)
     (bind-key "i" #'evil-scroll-page-up  messages-buffer-mode-map)
     (bind-key "k" #'evil-scroll-page-down  messages-buffer-mode-map)
     ))
